image:  mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview6-alpine3.9

before_script:
  - dotnet restore
  - dotnet new -u Microsoft.AspNetCore.Blazor.Templates
  - dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19104-04
  
pages:
  stage: deploy
  script:
  - mkdir public
  - dotnet publish -c Release -o output
  - cp -a -r ./output/* ./public
  artifacts:
    paths:
    - public
  only:
  - master