image:  microsoft/dotnet:3.0.100-preview6

before_script:
  - dotnet restore
  - dotnet new -u Microsoft.AspNetCore.Blazor.Tempates
  - dotnet new -i Microsoft.AspNetCore.Blazor.Templates::0.8.0-preview-19104-04
  
pages:
  stage: deploy
  script:
  - mkdir public
  - dotnet publish -c Release -o output
  - cp -a ./CVSite/output/CVSite/dist/* ./public
  artifacts:
    paths:
    - public
  only:
  - master